### ISSUE TITLE
format code using dart formatter

### ISSUE THREAD

**Issue by danrubel** [lukechurch/sintr#13]
Do we want to standardize on the format produced by the dart formatter?

**Comment by lukechurch** [comment]
Pah. Formatted code. Anyone would think you want to read it?

Yes. I'll do a single shot format on all of it once I've dropped landed the next little bit, and then I'll try and get into the habit of running the formatter before PR.

Thanks for the reminder.

**Comment by lukechurch** [comment]
Addressed in #17
